### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by tersekmatija** [cvlab-stonybrook/LearningToCountEverything#17]
Hey,

I am wondering on how many epochs have you pre-trained the provided model. I noticed that default value is `1500`. Is the provided model pre-trained on 1500 epochs?

And have you considered training with max pooling instead of mean, and if so, what were the results?
And also, have you considered training for multiple scales / feature maps?

Thank you for your answers in advance!

Best,
Matija

**Comment by Viresh-R** [comment]
Hey,
Pretrained model is the best model in terms of Val set MAE obtained after running the training for 1500 epochs. Note that we evaluate the model on Val set after each training epoch, and keep the model with the best Val MAE.

No, we didn't try max instead of mean pooling. But my guess is it would give similar/ slightly worse results than mean pooling.

We did try more scales and feature maps [earlier Resnet blocks than block3 and block4] with an earlier version of FamNet, but that didn't result in any significant performance gain.

Best,
Viresh

**Comment by jaideep11061982** [comment]
@hieulem @v-hoainm @tersekmatija @v-hoainm @sagniklp 
do you have pretrained weights for your paper,icouldnt find it anywhere

**Comment by hero-y** [comment]
Can you provide your pretrained model weight?
