### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by 1171000410** [cvlab-stonybrook/LearningToCountEverything#18]
Hello, 
We noticed the input of FamNet is the whole image and batch size equals to 1.
Have you tried random crop and increase the batch size?

Best wishes! Thank you for your answers in advance!

**Comment by Viresh-R** [comment]
Hey,
We did not use random crops with batchsize > 1 in the paper since the crop might not contain one or more of the exemplars. In order to use batchsize > 1, you'll need to address this case. One easy way of doing so would be to not use ROI pooling for those exemplars which go outside the crop, and computing the Resnet features for such exemplars independently.
