### ISSUE TITLE
The multi-scale feature extraction module consists of the first four blocks from a pre-trained ResNet-50 backbone

### ISSUE THREAD

**Issue by ONEISALL-h** [cvlab-stonybrook/LearningToCountEverything#29]
In the proposed model using ResNet-50 backbone instead of another deeper network. Is there any specific reason to use ResNet-50?

**Comment by Viresh-R** [comment]
Hey, we use Resnet-50 because of its widespread usage and proven track record of its usefulness for a wide range of Computer Vision tasks. But we expect FamNet to work with other Imagenet pretrained backbones as well, particularly those backbones which well for other dense prediction tasks like semantic segmentation.

**Comment by ONEISALL-h** [comment]
Thanks for your timely response! You are right, ResNet-50 appears in many works and has better results. For ResNet, it has other depths, such as 18, 34, 101, 152. Is there a particular reason for choosing ResNet-50, or is it simply because many jobs have adopted it?

**Comment by Viresh-R** [comment]
Resnet-50 works better than Resnet-18 and 34 in our case. And we didn't use 101 and 152 because we wanted to do a fair comparison with other competing approaches which use Resnet-50.

**Comment by jaideep11061982** [comment]
@Viresh-R could you share the pretrained weights for the model
